export const images = [ 
  "/img/00Black_owl.jpg"
, "/img/03_Black_nightSky.jpg"
, "/img/04_Black_pencilGlass.jpg"
, "/img/08_Blue_dancer.jpg"
, "/img/09_Blue_tango.jpg"
, "/img/10_Blue_jellyfish.jpg"
, "/img/12_Blue_noctilucent.jpg"
, "/img/15_Blue_bearGirl.jpg"
, "/img/19_Blue_krabi.jpg"
, "/img/20_Teal_pigBird.jpg"
, "/img/29_Green_seal.jpg"
, "/img/30_Green_birdOrator.jpg"
, "/img/32_Green_babyShoes.jpg"
, "/img/35_Green_forest.jpg"
, "/img/37_Green_girl.jpg"
, "/img/38_Green_disguise.jpg"
, "/img/39_Green_tightrope.jpg"
, "/img/40Yellow_lionCub.jpg"
, "/img/45_Yellow_cat.jpg"
, "/img/48_Brown_archaeologist.jpg"
, "/img/49_Brown_sparrows.jpg"
, "/img/50_Orange_clothes.jpg"
, "/img/55_Orange_hiphop.jpg"
, "/img/60_Orange_rider.jpg"
, "/img/65_Brown_horse.jpg"
, "/img/66_Red_lightning.jpg"
, "/img/67_Red_ballet.jpg"
, "/img/68_Red_dancers.jpg"
, "/img/70_Red_umbrellas.jpg"
, "/img/75_Pink_balloon.jpg"
, "/img/76_Pink-painting.jpg"
, "/img/81_Purple_woman.jpg"
, "/img/90_White_ZhangDi.jpg"
, "/img/92_White_snowboard.jpg"
, "/img/94_Grey_microscope.jpg"
, "/img/94_Grey_rotifer.jpg"
, "/img/95_Grey_labMouse.jpg"
, "/img/96_Grey_skateboard.jpg"
, "/img/97_Grey_waterDance.jpg"
, "/img/99_Grey_iceBubble.jpg"
]
// [
//   "/img/00Black_owl.jpg"
// , "/img/03_Black_nightSky.jpg"
// , "/img/04_Black_pencilGlass.jpg"
// , "/img/08_Blue_dancer.jpg"
// , "/img/09_Blue_tango.jpg"
// , "/img/10_Blue_jellyfish.jpg"
// , "/img/12_Blue_noctilucent.jpg"
// , "/img/15_Blue_bearGirl.jpg"
// , "/img/20_Teal_pigBird.jpg"
// , "/img/29_Green_seal.jpg"
// , "/img/30_Green_birdOrator.jpg"
// , "/img/32_Green_babyShoes.jpg"
// 
// , "/img/33_Green_rice.jpg"
//
// , "/img/35_Green_forest.jpg"
// , "/img/37_Green_girl.jpg"
// , "/img/38_Green_disguise.jpg"
// , "/img/39_Green_tightrope.jpg"
// , "/img/40Yellow_lionCub.jpg"
// , "/img/45_Yellow_cat.jpg"
// , "/img/48_Brown_archaeologist.jpg"
// , "/img/49_Brown_sparrows.jpg"
// , "/img/50_Orange_clothes.jpg"
// , "/img/55_Orange_hiphop.jpg"
// , "/img/60_Orange_rider.jpg"
// , "/img/65_Brown_horse.jpg"
// , "/img/66_Red_lightning.jpg"
// , "/img/67_Red_ballet.jpg"
// , "/img/68_Red_dancers.jpg"
// , "/img/70_Red_umbrellas.jpg"
// , "/img/75_Pink_balloon.jpg"
// , "/img/76_Pink-painting.jpg"
// , "/img/81_Purple_woman.jpg"
// , "/img/83_Purple_stars.jpg"
// , "/img/90_White_ZhangDi.jpg"
// , "/img/92_White_snowboard.jpg"
// , "/img/94_Grey_microscope.jpg"
// , "/img/94_Grey_rotifer.jpg"
// , "/img/95_Grey_labMouse.jpg"
// , "/img/96_Grey_skateboard.jpg"
// , "/img/97_Grey_waterDance.jpg"
// , "/img/99_Grey_iceBubble.jpg"
// ]